// Code generated by errcodegen. DO NOT EDIT.
package example

import "fmt"

// This file contains module example_module error codes.

// Define error code for errors from client side.
var (
	BadRequestErr = fmt.Errorf("%d: bad request", 41000601)
)

// Define error code for errors from server side.
var (
	ServerBusyErr = fmt.Errorf("%d: server busy", 51000601)
)
