// Code generated by errcodegen. DO NOT EDIT.
package example

import "fmt"

// This file contains module hello_module error codes.

// Define error code for errors from client side.
var (
	WrongParamErr = fmt.Errorf("%d: wrong param", 41000201)
)

// Define error code for errors from server side.
var (
	DBErr = fmt.Errorf("%d: db error", 51000201)
)
