// Code generated by errcodegen. DO NOT EDIT.
package errors

import "fmt"

// This file contains module example_module_2 error codes.

// Define error code for errors from client side.
var ()

// Define error code for errors from server side.
var (
	ServerDBErr = fmt.Errorf("%d: db error", 51000801)
)
